Repository solid-design-system/solid, pull requests merged in 2024-11, with the labels that each got.

#1514 docs: update tab template docs [skip chromatic]
  packages/components/src/components/badge/badge.stories.ts
  packages/components/src/components/icon/icon.stories.ts
  packages/components/src/components/tab-group/tab-group.stories.ts
  packages/components/src/components/tab-panel/tab-panel.stories.ts
  packages/components/src/components/tab/tab.stories.ts
  packages/components/src/templates/tab-group.stories.ts
  packages/components/src/templates/tab.stories.ts
Labels: rewrite docs

#1535 docs: add forms template docs [skip chromatic]
  packages/components/src/templates/forms.stories.ts
Labels: rewrite docs

#1462 docs: add sample A - 02 to header template docs [skip chromatic]
  packages/components/src/templates/header.stories.ts
Labels: rewrite docs

#1632 docs: update developer starting guide [skip chromatic]
  DEVELOPER_STARTING_GUIDE.md
Labels: documentation

#1641 fix: improve sd-button a11y
  packages/components/src/components/button/button.ts
Labels: A11y Audit
